name: "Add Content to Project Management Process Docs"
description: "Request to add new content or updates to an existing program management process document."
title: "[Process Doc Update]: "
labels: ["documentation", "process improvement"]
body:
  - type: dropdown
    id: process_doc
    attributes:
      label: "Which process document do you want to update? (If this is a new document, select '<new document>')"
      description: "Select the program management process document you want to add content to. If this is a new process doc, choose '<new document>'."
      options:
        - octoacme-project-management-overview.md
        - octoacme-project-initiation.md
        - octoacme-project-planning.md
        - octoacme-execution-and-tracking.md
        - octoacme-risks-and-communication.md
        - octoacme-release-and-deployment.md
        - octoacme-retrospective-and-continuous-improvement.md
        - octoacme-roles-and-personas.md
        - <new document>